export const actionsNames = {
    ADD_NEW_MESSAGE_FROM_DATA_BASE: "ADD_NEW_MESSAGE_FROM_DATA_BASE",
    GET_SIDEBAR_MENU_ITEMS: "GET_SIDEBAR_MENU_ITEMS",
    GET_MESSAGES_LIST: "GET_MESSAGES_LIST",
    CHANGE_TEXTAREA_MESSAGE: "CHANGE_TEXTAREA_MESSAGE",
    GET_USER_NAME: "GET_USER_NAME",
    CHANGE_USER_NAME: "CHANGE_USER_NAME"
}
